### PR TITLE
Static versioning and build improvements

### PR DESCRIPTION
**Pull request by gselzer**
This PR makes more changes than I originally planned for, but they're all good.

* Resorts to static versioning, managed in `pyproject.toml`.
* Moves all `setup.py`/`setup.cfg` data to `pyproject.toml`, *save for the new `flake8` config, as `flake8` has no support for `pyproject.toml` yet*.
  * Of note is the removal of [these lines](https://github.com/imagej/pyimagej/compare/static-versioning?expand=1#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L6-L9) from `setup.py`. My understanding is that Github is able to do this conversion  [automatically](https://stackoverflow.com/a/7658676).
* Adds Github actions for flaking and import sorting, as well as `pre-commit` hooks for those who wish to set them up. This PR also flakes and sorts the imports of all files.
* Renames the `test` folder to `tests`. This seems to be [good practice](https://github.com/pypa/sampleproject), and is what we do in other projects in our Python stack.
* Consolidates the Github actions for conda testing and code coverage into one action, to reduce our footprint on the Github actions servers.

### CODE REVIEW

**Comment by ctrueden** [comment]
> Of note is the removal of [these lines](https://github.com/imagej/pyimagej/compare/static-versioning?expand=1#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L6-L9) from setup.py. My understanding is that Github is able to do this conversion [automatically](https://stackoverflow.com/a/7658676).

It's not GitHub that that logic is present for, it's PyPI. So that the PyPI project page links correctly to GitHub with those links. One solution would be to expand them all to absolute links.

**Comment by gselzer** [comment]
> > Of note is the removal of [these lines](https://github.com/imagej/pyimagej/compare/static-versioning?expand=1#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L6-L9) from setup.py. My understanding is that Github is able to do this conversion [automatically](https://stackoverflow.com/a/7658676).
> 
> Good catch. But it's not GitHub that that logic is present for, it's PyPI. So that the PyPI project page links correctly to GitHub with those links. One solution would be to expand them all to absolute links.

Expand them to Github links?

**Comment by ctrueden** [comment]
How does this PR interact with #199? Should #199 be closed now?

**Comment by gselzer** [comment]
> 

I'll merge in the changes from that branch real quick

**Pull request merged**
