### PR TITLE
Missing step in the doc: conda init <SHELL_NAME>

### PR DESCRIPTION
**Pull request by Macarse**

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks @Macarse!

I've never seen this `conda init` step before. Is it new? Is this something you only do once, after installation? If so, I'd suggest we put it at step 2, before the conda-forge activation. What do you think?

Formatting wise, the subsequent lines of a numbered point in Markdown should be indented to line up with the first line.

**Comment by Macarse** [comment]
@ctrueden I would guess it's new. I never used miniconda before, so take this PR with a grain of salt. I just followed the cask installation and the init process basically takes care of setting up `bash_profile`. Not sure how this was done in the past.

**Comment by ctrueden** [comment]
@Macarse Thanks. I tried to tweak the commit and force push, but it looks like you have that permission disabled. Therefore I pushed the new commit directly to master.

**Comment by Macarse** [comment]
@ctrueden cool. thanks :)

**Comment by imagejan** [comment]
@ctrueden wrote:
> I've never seen this conda init step before. Is it new?

I've seen that for example on Windows: when you try running `conda activate yourEnv` in a console other than the Anaconda Prompt (e.g. in Git Bash), it warns you that the console is not set up for this yet, and instructs you to run `activate yourEnv` (without `conda`) or set up the console using `conda init bash` once.

**Pull request closed without merging**
