### PR TITLE
Add PythonScriptRunner to ObjectService to support scijava scripting-…

### PR DESCRIPTION
**Pull request by karlduderstadt**
This is a draft PR to support [scripting-python](https://github.com/karlduderstadt/scripting-python) in Fiji so that a conda python 3 scripting language can be used like all the other languages in Fiji.

At the moment, *all* python stdout and stderr are redirected to the script editor output. This might not be ideal if scripts are run in parallel. Another option would be to track threads and redirect output correctly.

I am not sure if this is ultimately the approach that is optimal. I was hoping this PR would provide a place for further discussion and tracking of what I have working so far. Maybe it would be more appropriate as a Draft but now I can't see how to change it back.

### CODE REVIEW

**Comment by karlduderstadt** [comment]
I made some small fixes and updates so that this PR reflects the best version from our tests. Now the ScriptContextWriter keeps track of the thread running the script and redirects outputs accordingly. So several scripts running in parallel will all receive the correct stdout. Also, errors during script execution are sent to the ErrorWriter. Previously, everything was going to the stdout. 

This PythonScriptRunner has been tremendously powerful for us. We believe this is a great way to integrate pyimagej into Fiji. Please let me know if you have any other thoughts or questions. Or if there is something else that needs to be tested to move this project forward.

**Comment by karlduderstadt** [comment]
Thanks for letting my build run. It seems to fail because the scripting-python classes and, most importantly, the [PythonScriptRunner](https://github.com/karlduderstadt/scripting-python/blob/master/src/main/java/org/scijava/plugins/scripting/python/PythonScriptRunner.java) interface used are not found on the class path. This is understandable since that [project](https://github.com/karlduderstadt/scripting-python) is still just under my account.

I used all the normal scijava licenses and am very happy if that moves somewhere else. I could move it to my lab organization and from there it could be build I guess, but seems better under scijava.

**Comment by imagejan** [comment]
I took the liberty to invite you to the `scijava` org, @karlduderstadt. This should allow you to migrate `scripting-python` to `scijava` in the repository settings.

**Comment by karlduderstadt** [comment]
Thanks @imagejan! I was able to migrate [scripting-python](https://github.com/scijava/scripting-python) over to scijava and setup GitHub CI. The next puzzle is to figure out how to make sure it shows up on the classpath over here. I don't see how that should work. First, I guess I should make a 0.1 release, but I am not sure if that would automatically put it on the classpath. Tips welcome.

**Comment by imagejan** [comment]
@karlduderstadt we should probably add `scripting-python` as a dependency in https://github.com/imagej/imagej2 or https://github.com/fiji/fiji, so that you have it when initializing with `ij = imagej.init()` or `ij = imagej.init('sc.fiji:fiji')`, respectively.

@ctrueden, what do you think?

**Comment by karlduderstadt** [comment]
I made PRs and implemented changes for the new scijava scripting language names 'Python (Jython)' and 'Python (PyImageJ)' 

What still needs to be done so this can be merged?

**Comment by ctrueden** [comment]
@karlduderstadt Finally, I'm making time to think about this work a little less superficially. Sorry it took me so long. Here are my initial thoughts:

* This logic is not PyImageJ-specific, and could live in scyjava. That would be more symmetrical with the SciJava layer being where the Python script language plugin lives on the Java side. The only PyImageJ-ish part currently is the use of the `ij` gateway to access the object service... but we could come up with somewhere else to stash a Python runner object.

* Using `@JImplements('org.scijava.plugins.scripting.python.PythonScriptRunner')` will require we have scripting-python on the classpath at runtime, I think. So at minimum, we'd need to put a guard around the creation of this class to ensure that scripting-python is indeed present before doing it. Otherwise, we break PyImageJ and/or scyjava for everyone using them for unrelated purposes.

* But there's no reason we need this special interface... you could instead implement something much more general (and type-unsafe) with e.g. `@JImplements('java.util.function.Function')` where the input is `Object` and the output is `Object`... and since it's Python code, it doesn't matter—you can just proceed with duck-typing as usual and grab properties like `.script`, `.vars`, and `.scriptContext` straight from the sole input argument.

* A challenge with using a general-purpose interface like `Function` is that there could conceivably be other `Function` object instances in the `ObjectService`'s index. Fortunately, the `ObjectService` now supports named objects thanks to @imagejan and @NicoKiaru, so we just need to add it with a highly-likely-to-be-unique name from the Python side (`objectService.addObject(obj, name)`). And then when retrieving objects of type `Function` on the Java side, filter them to only the one with the matching name (`getObjects(Function.class).stream().filter(obj -> "PythonScriptRunner".equals(objectService.getName(obj))).findFirst()`).

* Another challenge, if we move this logic upstream into scyjava, is how to use `ObjectService` at all. We need a `Context`. Here are a couple of approaches that spring to mind:
    * Add a `scyjava.context()` function that creates an `org.scijava.Context` complete with this special Python script runner function added to its object service. Then in PyImageJ, we change `imagej.init` to call `ctx = scyjava.context()` and feed that thing to `new ImageJ(ctx)` rather than using `new ImageJ()` and relying on the gateway to create it ourselves. The `context()` function would probably need to be `*args` and accept a list of Java classes, so that the context will contain the same services as it would if `new ImageJ()` were used.
    * Simpler: put the `PythonScriptRunner` class definition into scyjava, and add a function `scyjava.install_script_runner(context: 'org.scijava.Context')` that stuffs it into the `ObjectService` of the given context. Then on the PyImageJ side, call this method after constructing the ImageJ2 gateway. That way, projects using SciJava Common, but not built on non-ImageJ2, would still have an easy one-liner to gain access to the Python script engine.

@karlduderstadt I kind of like the `install_script_runner` approach. What do you think? If you like it, I'll make a PR in scyjava.

**Comment by ctrueden** [comment]
I am impatient, so I prototyped this idea in scyjava as scijava/scyjava#55. I'm closing this PR in favor of that one.

A couple of related things I was thinking about when I wrote it:

* I'd like to do something better than hijacking the whole `sys.stdout`. We also might need to do something about `stderr`.
* I was a little confused by the logic handling the script inputs, because the variable is called `inputs` even though it's really the locals of the script, which get modified during script execution. So then after the script `exec`s, the logic looping the `inputs` variable and pushing the values into `vars` *is* correct, but would be easier on my brain if we rename `inputs` to `script_locals` or some such, so I changed it.

@karlduderstadt If you have time to take a quick look at scijava/scyjava#55 and let me know if you like the direction, and see any problems with moving forward on it, I'd appreciate it very much. Once you give me the OK, then next week I'll try to make the corresponding changes to scripting-python and pyimagej, so that we can start testing it.

Finally, about Jep: the work moved forward quite a bit! It's still on the `jep` branch of scyjava. Unfortunately, over the course of doing this work, we concluded that Jep is not *quite* mature enough to enable seamless integration of Python into Fiji from the Java side—the biggest obstacle is ninia/jep#405, but we were also bitten by ninia/jep#439, and there may be additional wrinkles with other things like shared memory. So for now, we'll need to move forward with our original plan of augmenting the ImageJ Launcher to support launching in a "Python-first" mode via PyImageJ.

I'm excited to get this work finally completed and into production! Thanks again for pushing on it, and for your patience.

**Comment by karlduderstadt** [comment]
Thanks very much for taking a look at my PR in more depth! Everything you said makes a lot of sense. I didn't consider the problem of when people use PyImageJ without the PythonScriptRunner jar. That is a huge issue and I definitely agree it makes more sense over at scyjava.  Moving it to scyjava makes a lot of sense. I will go check out the changes over there and consider the new logic.

**Pull request closed without merging**
