### PR TITLE
Pin to known-working dependency versions and fix Travis CI build

### PR DESCRIPTION
**Pull request by imagejan**
Let's see if the Travis build works better with this.

### CODE REVIEW

**Comment by imagejan** [comment]
Hm, it looks like the conda environment was created successfully now (contrary to previous builds, where downgrading a python 3.8 env to python 3.7 failed for some reason, because dependencies could not be resolved).

However, the build now complains about not finding a JRE in a location pointing to a Java 11 path (despite OpenJDK8 being present in the conda env):

```
[ERROR]: Cannot locate JRE jar in /usr/local/lib/jvm/openjdk11
```

... although that might be false alarm.

---

The test errors look like the pyjnius issue https://github.com/kivy/pyjnius/issues/465

I'm trying now if pinning to `pyjnius=1.2.0` helps...

**Comment by imagejan** [comment]
Now I get a *different* error, related to JDK11 and `pyjnius`. Giving up for now.

**Comment by imagejan** [comment]
🚀 hooray: after pinning to `imglyb-0.3.5`, half of the builds (i.e. the MacOS build) succeed now 😄 

@ctrueden any idea on the other failure?

**Comment by imagejan** [comment]
Alright, the missing part was a `JAVA_HOME` that was set under Linux, but unset on MacOS.

This PR is now ready to be reviewed/merged.

**Comment by ctrueden** [comment]
Wow! Thanks for figuring this out, @imagejan! 🥇

**Pull request merged**
