### PR TITLE
Catch scyjava init error if JVM already running

### PR DESCRIPTION
**Pull request by hadim**
See https://github.com/imagej/pyimagej/issues/29 and https://github.com/scijava/scyjava/pull/8 for background.

### CODE REVIEW

**Comment by hadim** [comment]
@ctrueden and @hanslovsky : please at the last commit that solves the issue.

The downside now is the `imagej.init()` now returns a new `ImageJ` instance for each new call. I would like to prevent using global variables in Python. Can you think of anything I could use on the Java side to retrieve an already running `ImageJ` instance?

**Comment by hanslovsky** [comment]
Maybe `IJ.getInstance()` does the trick.

**Comment by hadim** [comment]
Isn't `IJ.getInstance()` an ImageJ1 function? I am sure there is an ImageJ2 way to do that...

**Comment by hanslovsky** [comment]
Yes, it is an IJ1 function. AFAIK IJ2 abandoned the singleton/static instance (and reasonably so IMHO), but @ctrueden will know better.

**Comment by hadim** [comment]
Ok. Let's wait for @ctrueden input. If it's not possible to do it the IJ2 way then I think we should use a global Python variable.

**Comment by hadim** [comment]
New proposal: the last commit uses a global variable `ij` to store the `ImageJ` instance and return it if the JVM is already running. I have also added an option to allow the user to create a new ImageJ instance if that's what he wants.

In the below screenshot look at the ImageJ instance address:

image

I don't have a strong feeling about the best behavior here as long as running `init()` twice don't raise an error so feel free to ask for something else.

**Pull request merged**
