### PR TITLE
Add RealType conversions

### PR DESCRIPTION
**Pull request by gselzer**
This PR adds support for converting `RealType` implementations.

To ensure conversions both from and *to* `RealTypes`, we need conversion to a unique type. This PR uses `ctypes` as the unique types. `ctypes` were chosen for three reasons:
1. They are part of the standard library
2. `ctypes` options account for signed vs. unsigned, different sizes, etc.
3. `ctypes` are mutable, like `RealType`s.

This PR only implements the conversions for corresponding `ctype` <-> `RealType` pairs. Thus only *some* `ctype`s can be converted to a `RealType` implementation, and only *some* `RealType`s can be converted to some `ctype`.

This PR is a draft as it depends on the work in scijava/scyjava#43. We require a release with that work; thus this PR should not be brought out of draft status until it depends on that new release.

### CODE REVIEW

**Comment by hinerm** [comment]
@gselzer so I tried testing with a locally installed dev pyimagej (post-https://github.com/scijava/scyjava/pull/43) and `test.sh` gives some errors, e.g.:

image

Any thoughts or suggestions?

**Comment by gselzer** [comment]
> @gselzer so I tried testing with a locally installed dev pyimagej (post-[scijava/scyjava#43](https://github.com/scijava/scyjava/pull/43)) and `test.sh` gives some errors, e.g.:
> 
> image
> 
> Any thoughts or suggestions?

Woah, @hinerm, it looks like your pytest parameterization is not correct. The pytest `FAILED` lines suggest you are trying to convert a `ctypes.c_long` to a `IntType`, which shouldn't be happening.

Can you check the parameterizations you have for `test/test_imagej.py::test_ctype_to_realType`? It should look like [this](https://github.com/imagej/pyimagej/blob/d14ebe3543c20805c3add592f6292131268748c0/test/test_imagej.py#L624)

**Comment by hinerm** [comment]
@ctrueden what are the current blockers to a scyjava release? Once that is done I can try to investigate further here

**Comment by ctrueden** [comment]
@hinerm The only blocker is scijava/scyjava#48.

**Comment by hinerm** [comment]
@gselzer this passes for me on WSL/ubuntu, but fails on windows still. :(

**Comment by gselzer** [comment]
That's really strange @hinerm. What version of Python are you running? Can you replicate in an IDE?

**Comment by hinerm** [comment]
python 3.8.10 on Windows.

pyimagej's tests don't seem to be auto-detecting as pytest tests in VS Code for me. How do you usually run them in an IDE?

**Comment by hinerm** [comment]
@gselzer changes pushed.. add any comments you'd like and then we can merge!

**Pull request merged**
